version: '3.8'

services:
  api:
    build:
      context: ./deliverlik-be
      target: development
    volumes:
      - ./deliverlik-be/:/usr/src/app/server
      - /usr/src/app/server/node_modules
    ports:
      - 3000:3000
    command: yarn dev
  client:
    build: 
      context: ./deliverlik-fe
      target: development
    volumes:
      - ./deliverlik-fe/:/usr/src/app/client
      - /usr/src/app/client/node_modules
    ports:
      - 5173:5173
    command: yarn dev

