version: '3.8'
services:
  api:
    build:
      context: ./deliverlik-be
      target: production

    ports:
      - 3000:3000
  client:
    build:
      context: ./deliverlik-fe
      target: production

    ports:
      - 5173:5173